### ISSUE TITLE
Android Studio 3.4.0应用插件异常

### ISSUE THREAD

**Issue by ysbing** [howardpang/androiddebughelper#1]
![image](https://user-images.githubusercontent.com/12974456/57425886-a81d8300-724f-11e9-93f3-6d9aa7130a18.png)
是不是没对gradle3.4.0版本做适配，还是什么问题？

**Comment by howardpang** [comment]
你是不是将那段代码放在了build.gradle文件了，需要放在setting.gradle里

**Comment by ysbing** [comment]
是啊，第一次见到这种用法，学习了
